# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "wp_comments_classifier"
  s.version = "0.0.1.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthias Schuetz"]
  s.date = "2012-04-29"
  s.description = "Classifies comments in a wordpress database based on previous classifications using naive bayes."
  s.email = "mschuetz@gmail.com"
  s.executables = ["classify_wp_comments"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "bin/classify_wp_comments",
    "lib/wp_comments_classifier.rb",
    "lib/wp_comments_classifier/database_classifier.rb",
    "lib/wp_comments_classifier/naivebayes.rb",
    "test/test_helper.rb",
    "test/test_naivebayes.rb",
    "test/test_wp_comments_classifier.rb",
    "wp_comments_classifier.gemspec"
  ]
  s.homepage = "https://github.com/mschuetz/wp_comments_classifier"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "A comment classifier for Wordpress blogs."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdbi>, [">= 0.9.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.7.0"])
      s.add_development_dependency(%q<rdbi-driver-sqlite3>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
    else
      s.add_dependency(%q<rdbi>, [">= 0.9.1"])
      s.add_dependency(%q<json>, [">= 1.7.0"])
      s.add_dependency(%q<rdbi-driver-sqlite3>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    end
  else
    s.add_dependency(%q<rdbi>, [">= 0.9.1"])
    s.add_dependency(%q<json>, [">= 1.7.0"])
    s.add_dependency(%q<rdbi-driver-sqlite3>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
  end
end

